### ISSUE TITLE
Broken on iOS 11 SDK.

### ISSUE THREAD

**Issue by benguild** [CooperRS/RMMultipleViewsController#9]
FYI

**Comment by CooperRS** [comment]
Sry, I missed the issue 🙂. I'll have a look now.

**Comment by CooperRS** [comment]
Hmm, not sure what the issue is? For me the demo project compiles just fine.

* Do you use any special build settings in your project?
* How do you integrate `RMMultipleViewsController`? CocoaPods?

**Comment by benguild** [comment]
It's an Objective-C project, and yes, Cocoa Pod.

**Comment by benguild** [comment]
No special build settings that I'm aware of? Are you sure you're targeting iOS 11 SDK with that project?

**Comment by CooperRS** [comment]
Yep, I checked that the Latest SDK (which is iOS 11 on Xcode 9) is being used. Can you give the concrete issue that appears when compiling?

**Comment by benguild** [comment]
This is what appears for me running a non-Storyboard project using both a native iPhone 7 and the iOS Simulator set to "iOS 11 / iPhone 7" ...

![screen shot 2017-09-02 at 19 30 35](https://user-images.githubusercontent.com/1185659/29994867-900010ee-9015-11e7-878c-3c5b0fccf357.png)

The sample project is fine, I'm assuming because Storyboards. ... Note the massive offset at the top of the `scrollView` as well, for some reason.

Same code works fine on iOS 9 and 10.3, no horizontal offset issue nor increased scroll offset.

**Comment by CooperRS** [comment]
Aha, so we are talking about a runtime issue. I assumed it was a compile time issue 🙂

**Comment by benguild** [comment]
Ah, I see. Any idea what might be causing it?

**Comment by CooperRS** [comment]
I think this is because of the new `UIScrolLView`behavior regarding content insets. Previously, `UIScrollViews`only had one inset property, called `contentInsets`. This property was used by both the system defined insets (like for navigation and tool bars) as well as application defined content insets. iOS 11 splits this up into `adjustedContentInset` (for system insets) and `contentInsets` (for application insets).

Can you try to set `contentInsetAdjustmentBehavior` of your scroll view to `never`?

**Comment by benguild** [comment]
Yeah, that fixes the larger inset, but the toggle in the `navigationBar` is still off-center.

Do you want to enumerate through the view controllers via this library and set that, or do we need to set it?

**Comment by benguild** [comment]
Yikes, look at iPad Air 2 in the Simulator on Xcode 9b6!

<img width="1017" alt="screenshot" src="https://user-images.githubusercontent.com/1185659/30093799-c29856d4-9302-11e7-95ef-dc992b199415.png">

**Comment by CooperRS** [comment]
Do you have a demo project for me demonstrating the problem with the toggle in the navigation bar? I tried to reproduce the problem with a Storyboard and a XIB but I was not able to do so.

> Do you want to enumerate through the view controllers via this library and set that, or do we need to set it?

I think if this is a requirement of the library, then the library should handle it. But first lets find out why the navigation bar has an offset in your case 🙂

**Comment by benguild** [comment]
Have you tried creating the view programmatically?

**Comment by benguild** [comment]
OK so good news, I moved some code around and sorted out the horizontal placement issue. I think it was an edge case based on order of operations and the new navigation bars.

Still need a fix for the scroll inset issue, though. Let me know if you have one please! :)

**Comment by CooperRS** [comment]
Can you take a look at [this iOS 11 branch](https://github.com/CooperRS/RMMultipleViewsController/tree/feature/ios-11). It should fix this problem 🙂.

**Comment by benguild** [comment]
Sure... We've already coded in a workaround temporarily but I have a "to-do" set to follow-up about this in the next update.

**Comment by benguild** [comment]
Seems to work fine!

**Comment by benguild** [comment]
Are you planning a new release/version?

**Comment by CooperRS** [comment]
Of course. I‘m going to fix Travis CI today and then we are good for a release.
